import "./globals.css";
import AuthProvider from './context/AuthProvider'

export const metadata = {
  title: "Next Auth App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
